version: 2
jobs:
  build1:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hello my friend"
  build2:
      docker:
        - image: circleci/node:8.9
      steps:
        - checkout
        - run: echo "Hello again"
workflows:
  version: 2
  builds:
    jobs:
      - build1
      - build2  
             